sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: '8'
install: npm install
script:
  - npm run lint
  - npm test
after_script:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master
  - /^greenkeeper/.*$/