sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: '8'
install: npm install
script:
  - npm run lint
  - npm test
after_script: "cat ./coverage/lcov.info | $(npm bin)/codecov"
branches:
  only:
  - master
  - /^greenkeeper/.*$/